version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/task_manager?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_here
      - WHATSAPP_API_URL=https://whatsapp-go.sebagja.id
      - WHATSAPP_USERNAME=ETAN
      - WHATSAPP_PASSWORD=121204l0vE!!@
      - WHATSAPP_PATH=whatsapp-account1
      - WHATSAPP_WEBHOOK_SECRET=superadmin
      - SERVER_PORT=8080
      - SESSION_TIMEOUT=3600
      - CACHE_TTL=1800
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=task_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
